require: rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: true
  DisplayCopNames: true
  TargetRubyVersion: 3.2.1
  Exclude:
    - 'bin/*'
    - 'spec/acceptance/fixtures/**/*'
    - 'spec/unit/fixtures/**/*'
    - 'vendor/gems/**/*'
    - '.github/**/*'

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

RSpec/ContextWording:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
