services:
  runway:
    container_name: runway
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: INFO
      CRYSTAL_ENV: production
    volumes:
      - config:/app/config

volumes:
  config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config
