projects:
  - name: project-1
    deployment:
      type: command
      location: local
      path: acceptance/projects/project-1/ # go to this path before running the command
      timeout: 5
      entrypoint: bash
      cmd: ["-c", "echo 'success' > result.txt && echo 'complete!'"]
    events:
      - type: file
        path: acceptance/projects/project-1/ship-it.txt
        cleanup: true # remove the file after the event
        schedule:
          interval: 3s
  - name: project-2
    deployment:
      type: command
      location: remote
      remote:
        auth: publickey
        host: ssh_server
        port: 22
        username: root
        public_key_path: /app/acceptance/ssh_server/keys/public/id_rsa.pub
        private_key_path: /app/acceptance/ssh_server/keys/private/id_rsa
        success_string: complete-remote
      timeout: 5
      entrypoint: bash
      cmd: ["-c", "'echo success > /app/logs/result-remote.txt && echo complete-remote'"] # shell escaping need to be fixed here
    events:
      - type: file
        path: acceptance/projects/project-2/ship-it.txt
        cleanup: true # remove the file after the event
        schedule:
          interval: 3s
