# To build the entire stack run 'make run'

services:
  runway:
    container_name: runway
    restart: 'no'
    build:
      context: ../../
      dockerfile: Dockerfile
    command: ["-c", "spec/acceptance/config/config.yml"]
    environment:
      LOG_LEVEL: DEBUG
      CRYSTAL_ENV: development
    volumes:
      - projects:/app/spec/acceptance/projects
      - config:/app/spec/acceptance/config
    # ports:
    #   - 8080:8080
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 15s

volumes:
  projects:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/spec/acceptance/projects
  config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/spec/acceptance/config
