# To build the entire stack run 'make run'

services:
  runway:
    container_name: runway
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      LOG_LEVEL: DEBUG
      CRYSTAL_ENV: development
    # ports:
    #   - 8080:8080
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 15s
