name: acceptance

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  acceptance:
    name: acceptance
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: fetch crystal version
        id: crystal-version
        run: echo "crystal=$(cat .crystal-version)"

      - name: install crystal
        uses: crystal-lang/install-crystal@v1.8.2
        with:
          crystal: ${{ steps.crystal-version.outputs.crystal }}

      - name: bootstrap
        run: script/bootstrap

      - name: set directory permissions (for ci)
        run: |
          chmod -R 777 ./acceptance
          chmod 700 ./acceptance/ssh_server/keys
          chmod 600 ./acceptance/ssh_server/keys/private/id_rsa
          chmod 600 ./acceptance/ssh_server/keys/public/id_rsa.pub

      - name: debug ssh key permissions
        run: |
          ls -l ./acceptance/ssh_server/keys
          id

      - name: pull docker images
        run: docker compose -f acceptance/docker-compose.acceptance.yml pull

      - uses: jpribyl/action-docker-layer-caching@c632825d12ec837065f49726ea27ddd40bcc7894 # pin@v0.1.1
        continue-on-error: true

      - name: acceptance
        env:
          LOG_LEVEL: DEBUG
          CRYSTAL_ENV: development
        run: script/acceptance
