name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: fetch ruby version
        id: ruby-version
        run: |
          version=$(cat .ruby-version)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - uses: ruby/setup-ruby@bc1dd263b68cb5626dbb55d5c89777d79372c484 # pin@v1.151.0
        with:
          ruby-version: ${{ steps.ruby-version.outputs.version }}
          bundler-cache: true

      - name: lint
        run: bundle exec rubocop -c .rubocop.yml src/ spec/
